### ISSUE TITLE
loxia excel解析,单元格是以下格式表达式时,得到的结果不正确

### ISSUE THREAD

**Issue by venusdrogon** [benjaliu/loxia2#2]
我的excel 是这样的,  AC22 表达式 是  =CONCATENATE(TEXT(F22,"yyyy-mm-dd"),"(",TEXT(F22,"aaaa"),") ",G22)

![2015-01-06_151120](https://cloud.githubusercontent.com/assets/3479472/5625476/64b5fc66-95b6-11e4-9fda-f304066118b9.png)

使用loxia 解析 得到的结果 是   `2015-01-07(42011.0) 14:00`
星期没有解析出来 

我看到源码 是使用 cellValue.getStringValue() 来解析的 

如果使用 cell.getRichStringCellValue().getString() 可以得到 正确的 结果 `2015-01-07(星期三) 14:00`

**Comment by benjaliu** [comment]
Fixed and deployed in the same version. Please clear your repository cache to use.

**Comment by venusdrogon** [comment]
有时间再来一起玩~
